=== Sheng-ZM/tms-go-apihub/schema/httpapi.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["id", "method", "requestContentType"],
  "properties": {
    "id": {
      "type": "string"
    },
    "url": {
      "type": "string"
    },
    "private": {
      "type": "string"
    },
    "method": {
      "type": "string",
      "enum": ["POST", "GET"]
    },
    "requestContentType": {
      "type": "string"
    },
    "args": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["in", "name", "value"],
        "properties": {
          "in": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "value": {
            "type": "object",
            "required": ["from"],
            "properties": {
              "from": {
                "type": "string"
              },
              "content": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "cache": {
      "type": "object",
      "required": ["expire", "format"],
      "properties": {
        "expire": {
          "type": "object",
          "required": ["from", "content"],
          "properties": {
            "from": {
              "type": "string"
            },
            "content": {
              "type": "string"
            }
          }
        },
        "format": {
          "type": "string"
        }
      }
    }
  }
}

=== Sheng-ZM/tms-go-apihub/example/httpapis/baidu_nlp_token.json
{
  "id": "baidu_nlp_token",
  "url": "https://aip.baidubce.com/oauth/2.0/token",
  "private": "baidu_nlp_key",
  "method": "GET",
  "requestContentType": "json",
  "args": [
    {
      "in": "query",
      "name": "grant_type",
      "value": {
        "from": "private",
        "content": "xgranttype"
      }
    },
    {
      "in": "query",
      "name": "client_id",
      "value": {
        "from": "private",
        "content": "xappkey"
      }
    },
    {
      "in": "query",
      "name": "client_secret",
      "value": {
        "from": "private",
        "content": "xsecret"
      }
    }
  ]
}

=== Sheng-ZM/tms-go-apihub/example/httpapis/baidu_nlp_parser.json
{
  "id": "baidu_nlp_lexer",
  "url": "https://aip.baidubce.com/rpc/2.0/nlp/v2/depparser",
  "private": "baidu_nlp_key",
  "method": "POST",
  "requestContentType": "json",
  "args": [
    {
      "in": "query",
      "name": "access_token",
      "value": {
        "from": "origin",
        "content": "token"
      }
    },
    {
      "in": "query",
      "name": "text",
      "value": {
        "from": "origin",
        "content": "text"
      }
    }
  ]
}

=== Sheng-ZM/tms-go-apihub/example/httpapis/baidu_image_classify_list.json
{
  "id": "baidu_image_classify_list",
  "url": "https://aip.baidubce.com/rest/2.0/image-classify/v1/animal",
  "private": "baidu_image_classify_key",
  "method": "POST",
  "requestContentType": "form",
  "args": [
    {
      "in": "query",
      "name": "access_token",
      "value": {
        "from": "origin",
        "content": "token"
      }
    },
    {
      "in": "body",
      "name": "imgUrl",
      "value": {
        "from": "origin",
        "content": "content"
      }
    }
  ]
}

=== Sheng-ZM/tms-go-apihub/example/httpapis/map_gettoken.json
{
  "id": "map_gettoken",
  "url": "http://10.128.86.64:8000/serviceAgent/rest/account/gettoken",
  "method": "POST",
  "private": "map_keys",
  "requestContentType": "json",
  "args": [
    {
      "in": "header",
      "name": "X-APP-ID",
      "value": {
        "from": "private",
        "content": "appid"
      }
    },
    {
      "in": "header",
      "name": "X-APP-KEY",
      "value": {
        "from": "private",
        "content": "appkey"
      }
    },
    {
      "in": "vars",
      "name": "user",
      "value": {
        "from": "private",
        "content": "user"
      }
    },
    {
      "in": "vars",
      "name": "password",
      "value": {
        "from": "private",
        "content": "password"
      }
    },
    {
      "in": "body",
      "name": "body",
      "value": {
        "from": "json",
        "json": {
          "userName": "{{.vars.user}}",
          "passwd": "{{.vars.password}}"
        }
      }
    }
  ],
  "cache": {
    "expire": {
      "from": "template",
      "content": "{{.result.expireTime}}"
    },
    "format": "20060102150405"
  }
}
