=== Sheng-ZM/tms-go-apihub/schema/httpapi-simple.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"title": "HTTPAPI schema文件",
	"required": [
		"id",
		"method",
		"requestContentType"
	],
	"properties": {
		"id": {
			"type": "string",
			"title": "HTTPAPI定义的标识"
		},
		"url": {
			"type": "string",
			"title": "不带参数的url地址",
			"description": "HTTPAPI，而是根据指定的目标地址，不包括任何查询参数"
		},
		"dynamicUrl": {
			"type": "object",
			"title": "动态生成的url地址",
			"description": "当url为空时，必须提供这个结构，用来动态生成URL（比如路径中含有appId），结构为标准的value结构",
			"required": [
				"from"
			],
			"properties": {
				"from": {
					"type": "string",
					"title": "参数来源",
					"description": "支持`literal`(直接从content里获取)，`query`(http query),`header`(http header),`private`(从秘钥文件读取),`origin`(原始报文body中的json),`env`(系统env)，heap(从原始报文和处理结果获取)，json(根据json生成字符串)，jsonRaw(根据json生成json结构体)，template(从content中生成),`func`(hub.FuncMap内部定义函数的名称)",
					"enum": [
						"origin",
						"private",
						"query",
						"header",
						"literal",
						"template",
						"heap",
						"json",
						"jsonRaw",
						"env",
						"func"
					]
				},
				"content": {
					"type": "string",
					"title": "参数名称或函数名称或template的内容"
				},
				"json": {
					"type": "object",
					"title": "json的输入值"
				},
				"args": {
					"type": "string",
					"title": "func的输入参数"
				}
			}
		},
		"description": {
			"type": "string",
			"title": "HTTPAPI的描述信息"
		},
		"private": {
			"type": "string",
			"title": "指定的秘钥文件名"
		},
		"method": {
			"type": "string",
			"title": "url请求方法",
			"description": "HTTP 请求方法，支持POST和GET",
			"enum": [
				"POST",
				"GET"
			]
		},
		"requestContentType": {
			"type": "string",
			"title": "请求内容类型",
			"description": "json映射为`application/json`，form映射为`application/x-www-form-urlencoded`，origin为取输入报文的ContentType，并直接转发输入报文的http body，none表示没有body,其他值则直接写入ContentType",
			"enum": [
				"json",
				"form",
				"orgin",
				"none"
			]
		},
		"args": {
			"type": "array",
			"title": "请求参数",
			"required": [
				"in",
				"name",
				"value"
			],
			"items": {
				"type": "object",
				"properties": {
					"in": {
						"type": "string",
						"title": "请求参数位置",
						"description": "参数位置。支持`query`，`header`,`body`, `vars`。前三者的值除了会放到发送报文里，还可以在模板通过.vars.访问，vars表示只进入.vars",
						"enum": [
							"header",
							"vars",
							"body",
							"query"
						]
					},
					"name": {
						"type": "string",
						"title": "请求参数名称"
					},
					"value": {
						"type": "object",
						"title": "参数值",
						"description": "标准value结构",
						"required": [
							"from"
						],
						"properties": {
							"from": {
								"type": "string",
								"title": "参数来源",
								"description": "支持`literal`(直接从content里获取)，`query`(http query),`header`(http header),`private`(从秘钥文件读取),`origin`(原始报文body中的json),`env`(系统env)，heap(从原始报文和处理结果获取)，json(根据json生成字符串)，jsonRaw(根据json生成json结构体)，template(从content中生成),`func`(hub.FuncMap内部定义函数的名称)",
								"enum": [
									"origin",
									"private",
									"query",
									"header",
									"literal",
									"template",
									"heap",
									"json",
									"jsonRaw",
									"env",
									"func"
								]
							},
							"content": {
								"type": "string",
								"title": "参数名称或函数名称或template的内容"
							},
							"json": {
								"type": "object",
								"title": "json的输入值"
							},
							"args": {
								"type": "string",
								"title": "func的输入参数"
							}
						}
					}
				}
			}
		},
		"cache": {
			"type": "object",
			"title": "是否支持缓存模式",
			"description": "HTTP请求是否支持缓存模式，如果支持，在过期时间内，将不会再向服务器请求，而是直接返回缓存内容",
			"required": [
				"from"
			],
			"required": [
				"expire",
				"format"
			],
			"properties": {
				"expire": {
					"type": "object",
					"title": "过期时间",
					"description": "指定过期时间的获取位置，标准value结构",
					"properties": {
						"from": {
							"type": "string",
							"title": "过期时间获取位置",
							"description": "获取过期时间的位置，是从header域中获取的话，则设置为header，如果从body中获取，则设置为template",
							"enum": [
								"template",
								"header"
							]
						},
						"content": {
							"type": "string",
							"title": "过期时间内容"
						},
						"json": {
							"type": "object",
							"title": "json的输入值"
						},
						"args": {
							"type": "string",
							"title": "输入参数"
						}
					}
				},
				"format": {
					"type": "string",
					"title": "过期时间格式",
					"description": "指定过期时间的解析格式。分为秒second和具体时间格式，如：20060102150405"
				}
			}
		}
	}
}

=== Sheng-ZM/tms-go-apihub/example/httpapis/手机归属地_mobile.json
{
    "id": "mobile",
    "description": "mobile",
    "url": "https://tenapi.cn/tel/",
    "method": "GET",
    "requestContentType": "json",
    "args": [
        {
            "in": "query",
            "name": "tel",
            "value": {
                "from": "literal",
                "content": "18888888888"
            }
        }
    ]
}

=== Sheng-ZM/tms-go-apihub/example/httpapis/kdxf_nlp_pos.json
{
  "id": "kdxf_nlp_pos",
  "description": "科大讯飞自然语言处理，词性标注。",
  "url": "https://ltpapi.xfyun.cn/v1/pos",
  "method": "POST",
  "private": "kdxf_keys",
  "requestContentType": "form",
  "args": [
    {
      "in": "header",
      "name": "X-Appid",
      "value": {
        "from": "private",
        "content": "appid"
      }
    },
    {
      "in": "header",
      "name": "X-Param",
      "value": {
        "from": "literal",
        "content": "eyJ0eXBlIjoiZGVwZW5kZW50In0="
      }
    },
    {
      "in": "header",
      "name": "X-CurTime",
      "value": {
        "from": "func",
        "content": "utc"
      }
    },
    {
      "in": "vars",
      "name": "apikey",
      "value": {
        "from": "private",
        "content": "apikey"
      }
    },
    {
      "in": "header",
      "name": "X-CheckSum",
      "value": {
        "from": "func",
        "content": "md5",
        "args": "apikey X-CurTime X-Param"
      }
    },
    {
      "in": "body",
      "name": "text",
      "value": {
        "from": "origin",
        "content": "content"
      }
    }
  ]
}

=== Sheng-ZM/tms-go-apihub/example/httpapis/kdxf_nlp_ke.json
{
  "id": "kdxf_nlp_ke",
  "description": "科大讯飞自然语言处理，提取关键词。",
  "url": "https://ltpapi.xfyun.cn/v1/ke",
  "method": "POST",
  "private": "kdxf_keys",
  "requestContentType": "form",
  "args": [
    {
      "in": "header",
      "name": "X-Appid",
      "value": {
        "from": "private",
        "content": "appid"
      }
    },
    {
      "in": "header",
      "name": "X-CurTime",
      "value": {
        "from": "func",
        "content": "utc"
      }
    },
    {
      "in": "header",
      "name": "X-Param",
      "value": {
        "from": "literal",
        "content": "eyJ0eXBlIjoiZGVwZW5kZW50In0="
      }
    },
    {
      "in": "vars",
      "name": "apikey",
      "value": {
        "from": "private",
        "content": "apikey"
      }
    },
    {
      "in": "vars",
      "name": "XCurTime",
      "value": {
        "from": "json",
        "content": "{{index .vars \"X-CurTime\"}}"
      }
    },
    {
      "in": "vars",
      "name": "XParam",
      "value": {
        "from": "json",
        "content": "{{index .vars \"X-Param\"}}"
      }
    },
    {
      "in": "header",
      "name": "X-CheckSum",
      "value": {
        "from": "json",
        "content": "{{md5 .vars.apikey .vars.XCurTime .vars.XParam}}"
      }
    },
    {
      "in": "body",
      "name": "text",
      "value": {
        "from": "origin",
        "content": "content"
      }
    }
  ]
}

=== Sheng-ZM/tms-go-apihub/example/httpapis/sm_send.json
{
  "id": "sm_send",
  "private": "sm_keys",
  "dynamicUrl": {
    "from": "private",
    "content": "url"
  },
  "method": "POST",
  "requestContentType": "json",
  "args": [
    {
      "in": "body",
      "name": "body",
      "value": {
        "from": "json",
        "json": {
          "type": 1,
          "to": "{{.origin.number}}",
          "content": "{{.origin.msg}}【佳信客服】"
        }
      }
    }
  ]
}
